### ISSUE TITLE
formatGenePred.pl produces zero sized files

### ISSUE THREAD

**Issue by adamfreedman** [hillerlab/CESAR2.0#10]
I ran formatGenePred.pl ${inputGenes} ${inputGenes}.forCESAR ${inputGenes}.discardedTranscripts after doing the necessary pre-processing steps. All relevant shell variables appear to exist, but, the output files are zero-sized. I double checked that the genepred file was valid with genePredCheck and there were no failures. No errors are printed to stdout so no inkling as to what is going wrong.

**Comment by MichaelHiller** [comment]
Can you pls send me your genePred file (or a few lines of it)? 
I'll have a look.

**Comment by adamfreedman** [comment]
I tried the basic genepred format:

rna-XM_012956089.1	NC_030677	-	133269	152620	152620	152620	6	133269,140925,143199,146034,151249,152381,	134186,141049,143418,146880,151541,152620,
rna-XM_018090860.1	NC_030677	-	158469	174433	174433	174433	5	158469,160350,162164,170432,174037,	159374,160474,162386,171221,174433,
rna-XM_012956191.2	NC_030677	-	192349	195109	195109	195109	2	192349,194935,	193426,195109,
rna-XM_002941730.2	NC_030677	-	211482	212022	212022	212022	1	211482,	212022,
rna-XM_012956192.2	NC_030677	+	218227	243623	243623	243623	5	218227,233350,235322,238854,242715,	218478,233453,235619,238978,243623,

as well as the extended version using the '-genePredExt' flag:

rna-XM_012956089.1      NC_030677       -       133269  152620  152620  152620  6       133269,140925,143199,146034,151249,152381,      134186,141049,143418,146880,151541,152620, 0
        gene-LOC100490505       none    none    -1,-1,-1,-1,-1,-1,
rna-XM_018090860.1      NC_030677       -       158469  174433  174433  174433  5       158469,160350,162164,170432,174037,     159374,160474,162386,171221,174433,     0       gene-LOC100490675   none    none    -1,-1,-1,-1,-1,
rna-XM_012956191.2      NC_030677       -       192349  195109  195109  195109  2       192349,194935,  193426,195109,  0       gene-LOC100489075       none    none    -1,-1,

**Comment by MichaelHiller** [comment]
I can reproduce the issue. The genePred looks find (genePredCheck does not complain).
I have asked Virag Sharma to look into it. 
More soon. 

Thanks for reporting this issue
Michael

**Comment by MichaelHiller** [comment]
Here is Virag's response. In short, it looks like you have non-coding transcripts in your genePred file. CESAR only considers coding transcripts. 

Virag will change the script to not drop non-coding transcripts but add them to the discarded file. 

"I just had a look. The input file contains non-coding genes where the translation start is the same as translation stop. So in short, there is no coding sequence.
The script filters out these transcripts, so at the end nothing is written to the output file.

Here is the relevant if statement in the script:
####
next if ($cdsStart == $cdsStop); ## These are not protein-coding genes. For RNA coding genes, cds_start = cds_stop. And we do not process them.
####
"

**Comment by MichaelHiller** [comment]
The script is updated. 
Best
Michael

**Comment by adamfreedman** [comment]
thanks for the quick debug and update!

**Comment by adamfreedman** [comment]
so .... the change to formatGenePred.pl leads to every transcript being discarded, and none being kept. this is for a genepred file derived from ncbi's xenopus annotation ... which should contain many protein-coding entries.

**Comment by adamfreedman** [comment]
i figured out the issue. discard of all transcripts results if the original genepred file is created with gtfToGenePred instead of gff3ToGenePred (I had annotations in both formats). might be worth mentioning on page that the former won't work

**Comment by MichaelHiller** [comment]
Hi Adam, 
will do. Thanks a lot
Michael
