### ISSUE TITLE
WARNING:Couldn't find declared stop codon in reference  

### ISSUE THREAD

**Issue by lizihe21** [hillerlab/CESAR2.0#11]
hi,when i run the step 3 for a reference and a query speice ,for almost every multi exon gene , i get the warning :
"WARNING! src/Model.c:254 multi_exon():	Couldn't find declared stop codon in reference 0. (counting from zero)" 
I wonder whether the reference or query lack stop codon when this warning emerge.
Thanks

**Comment by MichaelHiller** [comment]
Most likely the reference, as indicated in the error message. Pls check if the reference seq contains a stop codon. Also, try to add one and see if the warning disappears. 

You can also ignore the warning, but I would recommend to add the stop as it belongs to the gene.
