### ISSUE TITLE
cesar install concerns

### ISSUE THREAD

**Issue by jayramr** [hillerlab/CESAR2.0#18]
Hi Team,

Before building to bioconda package, i would need to install it manually and check. I followed below 

```
wget https://github.com/hillerlab/CESAR2.0/archive/refs/tags/1.0.tar.gz
cd CESAR2.0-1.0
make 
fatal: not a git repository (or any parent up to mount point /) 
<< throwing this error >>>
```

Again i tried with changing to kent/src
```
cd kent/src
make
cc -O -g -Wall -Wformat -Wimplicit -Wreturn-type -Wuninitialized -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -D_GNU_SOURCE -DMACHTYPE_x86_64   -Wall -Wformat -Wimplicit -Wreturn-type -Wuninitialized -I../inc -I../../inc -I../../../inc -I../../../../inc -I../../../../../inc -I../htslib   -o pngwrite.o -c pngwrite.c
pngwrite.c:7:10: fatal error: png.h: No such file or directory
    7 | #include "png.h"   // MUST come before common.h, due to setjmp checking  in pngconf.h
      |          ^~~~~~~
compilation terminated.
make[1]: *** [../inc/common.mk:420: pngwrite.o] Error 1
```

Please advise below

1. What will be the prerequisite software needed to run this software?
2. How to test once this is installed successfully -> for eg:- ./cesar --help

Because i would need to build all these in the bioconda package building recipe to make this work. 

Thanks
Jay

**Comment by MichaelHiller** [comment]
Hi Jay, 

I have never worked with github releases, but it looks like they don't include the .git dir with the git history. 
Still, despite this error, compiling works for me: 
cd CESAR2.0-1.0/
make
fatal: not a git repository (or any parent up to mount point /)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
gcc -O3 -std=c11 -DVERSION="\" added cd_acc/do\""   -c -o src/Fasta.o src/Fasta.c
fatal: not a git repository (or any parent up to mount point /)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
gcc -O3 -std=c11 -DVERSION="\" added cd_acc/do\""   -c -o src/State.o src/State.c
fatal: not a git repository (or any parent up to mount point /)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
gcc -O3 -std=c11 -DVERSION="\" added cd_acc/do\""   -c -o src/Params.o src/Params.c
fatal: not a git repository (or any parent up to mount point /)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
gcc -O3 -std=c11 -DVERSION="\" added cd_acc/do\""   -c -o src/Literal.o src/Literal.c
fatal: not a git repository (or any parent up to mount point /)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
...

./cesar 
Cesar  added cd_acc/do
Copyright 2017 MPI-CBG/MPI-PKS Peter Schwede

Align a pair of sequences using HMM.

Usage: cesar <fasta file>
             -c/--clade <human|mouse>
             -m/--matrix <matrix file>
...

To your questions: 
1) CESAR itself has no other required packages. But the entire workflow uses tools like mafSpeciesSubset from the UCSC browser https://github.com/ucscGenomeBrowser/kent 
While we provide a mini-kent, it would make more sense to install the entire kent repo. 

2) Please run
make test
fatal: not a git repository (or any parent up to mount point /)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
gcc -O3 -std=c11 -DVERSION="\" added cd_acc/do\"" -o CESAR src/Fasta.o src/State.o src/Params.o src/Literal.o src/Arguments.o src/Alignment.o src/Cesar.o src/Model.o src/Profile.o src/EmissionTable.o src/Matrix.o src/Viterbi.o src/Sequence.o src/HMM.o src/Logodd.o -lm -lc
mv CESAR cesar
tests.sh ./cesar
Checking for correct behaviour.
./extra/samples/example1.in... OK
./extra/samples/sample0.in... OK
./extra/samples/sample1.in... OK
./extra/samples/sample2.in... OK
./extra/samples/sample3.in... OK
./extra/samples/sample4.in... OK
./extra/samples/sample5.in... OK
./extra/samples/sample6.in... OK
./extra/samples/sample7.in... OK


Thx
- Michael

**Comment by kirilenkobm** [comment]
Hi,

makefile at line 5 has the following expression:
VERSION=-DVERSION="\"$(shell git log -n1 --pretty=format:%h%d) added cd_acc/do\""
This command just crashes because the downloaded archive has no .git directory.
The build itself should work fine I guess.

**Comment by kirilenkobm** [comment]
@jayramr pls ignore the kent subdirectory
- CESAR itself, as a standalone tool, does not need it.
- It contains the source code for some UCSC genome browser-related binaries. Most of them already can be installed via conda or/and packed into docker containers.

**Comment by MichaelHiller** [comment]
I removed the git version from the Makefile. 
Should work now without errors. 
Pls use https://github.com/hillerlab/CESAR2.0/archive/refs/tags/1.01.tar.gz

**Comment by jayramr** [comment]
Thanks I will test this week and update you if any errors.

**Comment by jayramr** [comment]
It is reflecing in anaconda now https://anaconda.org/bioconda/cesar
