### ISSUE TITLE
perl system call using bash specific feature

### ISSUE THREAD

**Issue by gh-ahardin** [hillerlab/CESAR2.0#2]
It seems that line 192 of annotateGenesViaCESAR.pl is trying to use 'set -o pipefail' which is a bash shell function and will not work on sh or dash (the default in Ubuntu). I fixed that line by changing it to my $mafExtractCall = "/bin/bash -c 'set -o pipefail; mafExtract -region=$chrRef:$refStart-$refStop $mafIndex stdout|mafSpeciesSubset std\
in speciesList=$speciesList,$reference species.lst=NULL $mafFile'";

**Comment by MichaelHiller** [comment]
Thanks Aaron. I incorporated your change in the script.
