### ISSUE TITLE
Genome alignment

### ISSUE THREAD

**Issue by biouserPD** [hillerlab/CESAR2.0#3]
Hi,
I have a doubt about the genome alignment input. I see that in the workflow CESAR2 needs a genome alignment (reference genome and query genome) in  maf format. Which software we can use for this task? Do you have any suggestion? 
Thanks in advance
Max

**Comment by MichaelHiller** [comment]
Hi Max, 

we have been using the UCSC workflow of lastz/chain/net to obtain pairwise genome alignments. The UCSC script doBlastzChainNet.pl automates these steps and produces a pairwise maf output file (kent source code). 

- Michael
