### ISSUE TITLE
CESAR on plant genomes

### ISSUE THREAD

**Issue by dcopetti** [hillerlab/CESAR2.0#4]
Hello,

I am wondering if, as is, CESAR will work as well on plant genomes.
More specifically, I am thinking to use it to predict coding regions of a new grass species using a closely-related reference grass (brachypodium, barley, ...) whose annotation is known. How much does relatedness really matter? E.g. is it better to use a very close good reference or rather a more distant well-annotated species?

Also, does CESAR's output constitute a final gene annotation or is it more to be used as another evidence for creating final gene models from other sets (ab initio prediction, EST alignment, ...)?
Thanks,
Dario

**Comment by MichaelHiller** [comment]
Hi Dario, 
we have never tested CESAR2 on plants, but the genetic code and splice sites are similar. 

CESAR2 only annotates the coding portions of genes, however this is very accurate, especially for closely related species. Typically it helps to chose the species as reference that has the best gene annotation, and if possible closely-related species. The more distant species are, the more difficult the genome alignment gets. 

- Michael
