### ISSUE TITLE
-speciesList is not a valid option Error

### ISSUE THREAD

**Issue by kim2039** [hillerlab/CESAR2.0#7]
Hello,

I have some troubles, on Ubuntu 19.10

I tried to run "Mini example of annotating 2 genes in one query genome", however some issues about OpenSSL had occurred. (This problem had occurred on Ubuntu 17.10, too)

The issue seems to be from mafSpeciesSubset, 
```
$ ~/Bioinformatics/tools/CESARTest/CESAR2.0/tools/mafSpeciesSubset

/home/kim/Bioinformatics/tools/CESARTest/CESAR2.0/tools/mafSpeciesSubset: /lib/x86_64-linux-gnu/libssl.so.10: version `libssl.so.10' not found (required by /home/kim/Bioinformatics/tools/CESARTest/CESAR2.0/tools/mafSpeciesSubset)
/home/kim/Bioinformatics/tools/CESARTest/CESAR2.0/tools/mafSpeciesSubset: /lib/x86_64-linux-gnu/libcrypto.so.10: version `libcrypto.so.10' not found (required by /home/kim/Bioinformatics/tools/CESARTest/CESAR2.0/tools/mafSpeciesSubset)
```
So, I downloaded latest UCSC tools and replaced. 
(Downloaded from http://hgdownload.soe.ucsc.edu/admin/exe/linux.x86_64/)

The error about openSSL seems to be solved, but a new issue had occurred,
```
kim@kim-Ubuntu:~/Bioinformatics/tools/CESAR2.0/extra/miniExample$ annotateGenesViaCESAR.pl SNRNP25 hg38_oryAfe1.bb twoGenes.gp.forCESAR hg38 oryAfe1 CESARoutput 2bitDir $profilePath -maxMemory 1

Processing gene 'SNRNP25'
-specieslist is not a valid option
Error running '/bin/bash -c 'set -o pipefail; mafExtract -region=chr16:53989-54058 hg38_oryAfe1.bb stdout|echo stdin|mafSpeciesSubset stdin specieslist=oryAfe1,hg38 species.lst=NULL /dev/shm/exon.maf.C5j9jZxF0''
```

How do I solve this problem?

Thanks,
Kim

**Comment by MichaelHiller** [comment]
Hi Kim,

I assume that you have installed the UCSC kent source code, which provides the original mafSpeciesSubset that does not have the -speciesList option. We added this in the code provided.

Pls run
which mafSpeciesSubset
to check if that refers to the binary in the tools/ directory. 

If not, pls set
export PATH=`pwd`/tools:$PATH
such that the shell first looks into the tools dir.

Let me know if that does not work.
Michael

**Comment by kim2039** [comment]
Hello, Michael,

I ran 
$ which mafSpeciesSubset
and it worked and show /tools/mafSpeciesSubset binary file.

And both of original mafSpeciesSubset binary and your mafSpeciesSubset binary seem not to work, same error messages like below.

your binary
```
$ annotateGenesViaCESAR.pl SNRNP25 hg38_oryAfe1.bb twoGenes.gp.forCESAR hg38 oryAfe1 CESARoutput 2bitDir $profilePath -maxMemory 1

Processing gene 'SNRNP25'
mafSpeciesSubset: /lib/x86_64-linux-gnu/libssl.so.10: version `libssl.so.10' not found (required by mafSpeciesSubset)
mafSpeciesSubset: /lib/x86_64-linux-gnu/libcrypto.so.10: version `libcrypto.so.10' not found (required by mafSpeciesSubset)
Error running '/bin/bash -c 'set -o pipefail; mafExtract -region=chr16:53989-54058 hg38_oryAfe1.bb stdout|mafSpeciesSubset stdin NULL /dev/shm/exon.maf.SlBrW0N3l -speciesList=oryAfe1,hg38''
```

original latest binary
```
$ annotateGenesViaCESAR.pl SNRNP25 hg38_oryAfe1.bb twoGenes.gp.forCESAR hg38 oryAfe1 CESARoutput 2bitDir $profilePath -maxMemory 1

Processing gene 'SNRNP25'
-speciesList is not a valid option
Error running '/bin/bash -c 'set -o pipefail; mafExtract -region=chr16:53989-54058 hg38_oryAfe1.bb stdout|mafSpeciesSubset stdin NULL /dev/shm/exon.maf.bpAlrDf2M -speciesList=oryAfe1,hg38''
```

I tried to run original binary and made symbolic link to libssl.so.10 and libcrypto.so.10, but don't work because of difference of the version.

Thanks,
Kim

**Comment by MichaelHiller** [comment]
Hi Kim, 

the problem is that the provided mafSpeciesSubset does not work due to issues with the libraries. 

I have now added a lightweight kent source with the source code of mafSpeciesSubset. 
Please clone CESAR2.0 again and follow the updated instructions. 

It should work now. If not, pls let me know. 

Thanks a lot
Michael

**Comment by kim2039** [comment]
Hello Michael,

Thank you!!
It works!

However, to run "Mini example", I had to replace some binary files (overlapSelect, bedSort, twoBitToFa) with latest version because of same errors,

> \`libssl.so.10' not found
> \`libcrypto.so.10' not found 

But other error didn't occur.

Thanks a lot,
Kim
