### ISSUE TITLE
mafIndex: Anc00refChr0 not found

### ISSUE THREAD

**Issue by sjswuitchik** [hillerlab/CESAR2.0#8]
Hello, 

I am trying to index my MAF file (output of CACTUS whole-genome alignment HAL converted to MAF using HAL Tools) but get the error `Anc00refChr0 is not found in chromosome sizes file \ command exited with 255: bedToBigBed temppLlCQT 2bitdir galloanserae.bb -type=bed4+1` when I run `tools/mafIndex galloanserae.maf galloanserae.bb -chromSizes=2bitdir`

I've tried pointing the `-chromSizes` option at multiple directories and chrom.sizes files in case I wasn't understanding that option, but receive the same error. If there is any feedback or advice for how I can move forward, it would be greatly appreciated! 

Thank you for your time, 

Sara

**Comment by MichaelHiller** [comment]
Hi Sara, 
I have never worked with HAL converted to MAF files, so I make a few guesses of what could be the issue.

Cactus is reference free, but should support projecting the multi ali to a reference species (one with well annotated genes, chicken??). The chromSizes parameter should point to the dir of that ref species. In the chrom.sizes file, each reference species scaffold/chrom must have an entry. 

From Anc00refChr0, it may be that you have set a reconstructed ancestor as the reference. This would not work, as you won't have annotated genes for this ancestor (??). 

Pls let me know if these guesses were helpful. If not, send me a small part of the maf you generated and the chrom.size file. 

Thanks
Michael

**Comment by sjswuitchik** [comment]
Hi Michael, 

That makes sense, I will try the conversion with galGal6 as the root. I will let you know how it goes! 

Thank you for your suggestions, 

Sara

**Comment by sjswuitchik** [comment]
Hi Michael, 

I was able to convert my HAL alignment with galGal as the root, but still get an error (`NC_006088 is not found in chromosome sizes file \ command exited with 255: bedToBigBed tempDfy6Qi 2bitdir/galGal galloanserae_rooted.bb -type=bed4+1`) when I run:

`tools/mafIndex galloanserae_rooted.maf galloanserae_rooted.bb -chromSizes=2bitdir/galGal`

When I grep NC_006088 in galGal.chrom.sizes, it returns `NC_006088.5	197608386` and there are many entries with gal.Gal.NC_006088.5 in the MAF file. When I look at tempDfy6Qi, there are many lines where the first column is NC_006088. I'm sorry if this isn't enough information to diagnose the error, but please let me know if you have any advice. 

Thanks!

Sara

**Comment by MichaelHiller** [comment]
Hi Sara, 

I believe the maf file must have the exact scaffold name (NC_006088.5 not NC_006088) as listed in the chrom.size file. 
Could you test this on a mini example, where you replace NC_006088 by NC_006088.5 ?

**Comment by sjswuitchik** [comment]
Hi Michael, 

The scaffold name is NC_006088.5 in both the chrom.sizes file as well as the MAF, but the scaffold suffixes (eg/ .5, .1, .2 etc.) are not present in the temp files that are output with the bedToBigBed error.

**Comment by MichaelHiller** [comment]
Can you extract a small enough example to send via email?

**Comment by sjswuitchik** [comment]
Hi Michael, I tried replacing the scaffold names in the chrom.sizes file to remove the numerical suffix just in case and it seems to be running properly - I'll keep you posted, thank you for your suggestions! 

Sara

**Comment by sjswuitchik** [comment]
This seemed to work! Thank you again for your time and help.

Sara

**Comment by MichaelHiller** [comment]
Excellent.
