### ISSUE TITLE
Missing stop codon in reference (similar to closed Issue #6)

### ISSUE THREAD

**Issue by sjswuitchik** [hillerlab/CESAR2.0#9]
Hi Michael, 

When running `./jobList` I get the repetitive error of `WARNING! src/Model.c:254 multi_exon():  Couldn't find declared stop codon in reference 0. (counting from zero)`

I realize this was addressed in the closed issue #6 but I don't understand where to add the missing stop codon in the reference, or more specifically I'm not sure which file to add the stop codon to? 

Thank you for your time and help!

Sara

**Comment by MichaelHiller** [comment]
Hi Sara, 

CESAR expects to get as input complete transcripts, or more precise complete CDS. 
That means every input transcript from the reference should have a CDS annotation that starts with an ATG and ends with a stop codon. CESAR logically treats the start and stop of the first and last coding exon as the 'missing' splice site and will try to find a start/stop in case that has been shifted. 

You likely include incomplete transcripts that lack start or, in this case, a stop codon.
Best is to correct these transcripts in the reference (apparently they lack the lack the real last coding exon of correct coding exon end) or to exclude them.

Best
Michael

**Comment by sjswuitchik** [comment]
Hi Michael, 

I understand and am working on this now. Thanks again! 

Sara
